### ISSUE TITLE
Refactor and modularize project

### ISSUE THREAD

**Issue by willmendesneto** [willmendesneto/keepr#5]
Refactor project for optimize your components usage. For example:

* More abstraction in directives, like `kpMask`, for remove mask logic in a filter/service/factory/etc and this directive use it.
* Many abstractions in services/factories/directives project;

**Comment by willmendesneto** [comment]
@johannesjo https://github.com/willmendesneto/ngOfflineModel

**Comment by johannesjo** [comment]
@willmendesneto very cool, thank you! just one single thing is missing: the bower registration of the package  :)

**Comment by willmendesneto** [comment]
@johannesjo , the `ngOfflineModel` already registered in bower and ng-modules. Please take a look in README.md file of the new repository for more informations.

**Comment by johannesjo** [comment]
@willmendesneto Thank you very much! This module will be very handy!

**Comment by glebmachine** [comment]
+1
You definitely should spit all this staff by modules!

**Comment by willmendesneto** [comment]
@johannesjo @glebmachine I'm closing this issue because I created [ngOfflineModel](https://github.com/willmendesneto/ngOfflineModel) and [OfflineModel](https://github.com/willmendesneto/offline-model) repositories.

Sorry for delay and thanks guys!
